const HTML = {
    formReg: document.getElementById('formReg'),
    passReg: document.getElementById('passReg'),
    passReg2: document.getElementById('passReg2'),
    errorPassKeyReg: document.getElementById('error_passkey_Reg'),
    boxPassLogin: document.getElementById('box-passLogin'),
    navUser: document.getElementById('nav-user'),
    dropdownUser: document.getElementById('dropdown-user'),
    slidebarHome: document.getElementById('slidebar-home'),
    navHome: document.getElementById('nav-home'),
    closedSlidebar: document.getElementById('closed-slidebar'),
    sshServer: document.getElementById('ssh-server'),
    sshCliente: document.getElementById('ssh-cliente'),
    sshClipServer: document.getElementById('copy-ssh-server'),
    sshClipCliente: document.getElementById('copy-ssh-cliente'),
    registroUser: document.getElementById('registroUser'),
    addUsers: document.getElementById('addUsers'),
    passwdUser: document.getAnimations('passwdUser'),
    reapeatPasswdlUser: document.getElementById('reapeatPasswdlUser'),
    errorPass: document.getElementById('errorPasswd'),
    afterUsers: document.getElementById('afterUsers'),
    beforeUsers: document.getElementById('beforeUsers'),
    checkBoxClass: document.getElementsByClassName('check-box'),
}